name: Assignment4_Github_Actions
on:
  push:
    branches:
    - master

  workflow_dispatch:
    inputs:
      terraform_operation:
        description: "Terraform operation: plan, apply, destroy"
        required: true
        default: "apply"
        type: choice
        options:
          - plan
          - apply
          - destroy
jobs:
  terraform:
    
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    
    steps:

      - name: checkout_Teraaform_code_from_github_repo
        uses: actions/checkout@v1

      - name: install_terraform_on_github_provisioned_server
        uses: hashicorp/setup-terraform@v1

      - name: terraform_format_command
        run: terraform fmt
      
      - name: terraform_initialize_command
        run: terraform init -lock=false
      
      - name: terraform_planning_command
        run: terraform plan -lock=false
        if: "${{ github.event.inputs.terraform_operation == 'plan' }}"

    
      - name: terraform_apply_command
        run: terraform apply --auto-approve -lock=false
        if: "${{ github.event.inputs.terraform_operation == 'apply' }}"


      - name: terraform_destroy_command
        run: terraform destroy --auto-approve -lock=false
        if: "${{ github.event.inputs.terraform_operation == 'destroy' }}"

